/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export interface CompareCommits {
  aheadBy?: number;
  baseCommit?: object;
  behindBy?: number;
  commits?: object[];
  diffUrl?: string;
  files?: object[];
  htmlUrl?: string;
  patchUrl?: string;
  permalinkUrl?: string;
  status?: string;
  totalCommits?: number;
  url?: string;
}
