/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export interface Gist {
  comments?: number;
  comments_url?: string;
  created_at?: string;  // Timestamp in ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ.
  description?: string;
  files?: object;
  forks?: object[];
  git_pull_url?: string;
  git_push_url?: string;
  history?: object[];
  html_url?: string;
  id?: string;
  public?: boolean;
  url?: string;
  user?: object;
}
