/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export interface Release {
  assets?: object[];
  assetsUrl?: string;
  author?: object;
  body?: string;
  createdAt?: string;
  draft?: boolean;
  htmlUrl?: string;
  id?: number;
  name?: string;
  prerelease?: boolean;
  publishedAt?: string;
  tagName?: string;
  tarballUrl?: string;
  targetCommitish?: string;
  uploadUrl?: string;
  url?: string;
  zipballUrl?: string;
}
