/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export interface Repo {
  cloneUrl?: string;
  /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
  createdAt?: string;
  description?: string;
  fork?: boolean;
  forks?: number;
  forksCount?: number;
  fullName?: string;
  gitUrl?: string;
  hasDownloads?: boolean;
  hasIssues?: boolean;
  hasWiki?: boolean;
  homepage?: string;
  htmlUrl?: string;
  id?: number;
  language?: string;
  masterBranch?: string;
  mirrorUrl?: string;
  name?: string;
  openIssues?: number;
  openIssuesCount?: number;
  organization?: object;
  owner?: object;
  /** Is present when the repo is a fork. Parent is the repo this repo was forked from. */
  parent?: object;
  private?: boolean;
  /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
  pushedAt?: string;
  size?: number;
  /** Is present when the repo is a fork. Source is the ultimate source for the network. */
  source?: object;
  sshUrl?: string;
  svnUrl?: string;
  /** ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ */
  updatedAt?: string;
  url?: string;
  watchers?: number;
  watchersCount?: number;
}
