/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpResponse, HttpEvent } from '@angular/common/http';
import { Observable } from 'rxjs';import { HttpOptions } from './types';

import * as models from './models';
export interface APIClientInterface {
  /**
   * Arguments object for method `getItems`.
   */
  getItemsParams?: {
    pageSize: number,
    /** page number */
    page: number,
  };

  /**
   * Get items list
   * Response generated for [ 200 ] HTTP response code.
   */
  getItems(
    args: Exclude<APIClientInterface['getItemsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.ItemList>;
  getItems(
    args: Exclude<APIClientInterface['getItemsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.ItemList>>;
  getItems(
    args: Exclude<APIClientInterface['getItemsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.ItemList>>;

  /**
   * Arguments object for method `getItemModels`.
   */
  getItemModelsParams?: {
    pageSize: number,
    /** page number */
    page: number,
  };

  /**
   * Get item models list
   * Response generated for [ 200 ] HTTP response code.
   */
  getItemModels(
    args: Exclude<APIClientInterface['getItemModelsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getItemModels(
    args: Exclude<APIClientInterface['getItemModelsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getItemModels(
    args: Exclude<APIClientInterface['getItemModelsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `getPetsId`.
   */
  getPetsIdParams?: {
    id: string,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getPetsId(
    args: Exclude<APIClientInterface['getPetsIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Pet[]>;
  getPetsId(
    args: Exclude<APIClientInterface['getPetsIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Pet[]>>;
  getPetsId(
    args: Exclude<APIClientInterface['getPetsIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Pet[]>>;

  /**
   * Arguments object for method `deletePetsId`.
   */
  deletePetsIdParams?: {
    id: string,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  deletePetsId(
    args: Exclude<APIClientInterface['deletePetsIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deletePetsId(
    args: Exclude<APIClientInterface['deletePetsIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deletePetsId(
    args: Exclude<APIClientInterface['deletePetsIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getCustomers(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<(models.Customer[]) | null>;
  getCustomers(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<(models.Customer[]) | null>>;
  getCustomers(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<(models.Customer[]) | null>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getDictionaries(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Dictionary>;
  getDictionaries(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Dictionary>>;
  getDictionaries(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Dictionary>>;

  /**
   * Arguments object for method `getFileId`.
   */
  getFileIdParams?: {
    id: string,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getFileId(
    args: Exclude<APIClientInterface['getFileIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<File>;
  getFileId(
    args: Exclude<APIClientInterface['getFileIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<File>>;
  getFileId(
    args: Exclude<APIClientInterface['getFileIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<File>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getRandomObject(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getRandomObject(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getRandomObject(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getRandomModel(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getRandomModel(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getRandomModel(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getRandomString(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<string>;
  getRandomString(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<string>>;
  getRandomString(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<string>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getDictionary(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<{ [key: string]: number }>;
  getDictionary(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<{ [key: string]: number }>>;
  getDictionary(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<{ [key: string]: number }>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  getArrayOfDictionaries(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<{ [key: string]: number }[]>;
  getArrayOfDictionaries(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<{ [key: string]: number }[]>>;
  getArrayOfDictionaries(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<{ [key: string]: number }[]>>;

  /**
   * Arguments object for method `firestoreProjectsDatabasesDocumentsCommit`.
   */
  firestoreProjectsDatabasesDocumentsCommitParams?: {
    /**
     * - error format
     * - 1 V1
     * - 2 V2
     * 
     */
    wololo?: models.NumberEnumParam,
    /**
     * Data format for response.
     * If not set, server will use the default value: json
     */
    alt?: models.StringEnumParam,
    /** OAuth access token. */
    accessToken?: string,
    /**
     * Pretty-print response.
     * If not set, server will use the default value: true
     */
    pp?: boolean,
    /**
     * should pretty print
     * If not set, server will use the default value: true
     */
    prettyPrint?: boolean,
    /**
     * this params is deprecated
     * @deprecated this parameter has been deprecated and may be removed in future.
     */
    simpleQueryParam?: string,
    /** @deprecated this parameter has been deprecated and may be removed in future. */
    simpleArrayQueryParam?: number[],
    body?: models.Data,
    /** The database name. In the format `database:{{name}}` */
    database: string,
  };

  /**
   * Commits a transaction, while optionally updating documents.
   * Response generated for [ 200 ] HTTP response code.
   */
  firestoreProjectsDatabasesDocumentsCommit(
    args: Exclude<APIClientInterface['firestoreProjectsDatabasesDocumentsCommitParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Dictionary>;
  firestoreProjectsDatabasesDocumentsCommit(
    args: Exclude<APIClientInterface['firestoreProjectsDatabasesDocumentsCommitParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Dictionary>>;
  firestoreProjectsDatabasesDocumentsCommit(
    args: Exclude<APIClientInterface['firestoreProjectsDatabasesDocumentsCommitParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Dictionary>>;

  /**
   * Arguments object for method `postReposOwnerRepoGitBlobs`.
   */
  postReposOwnerRepoGitBlobsParams?: {
    /** Name of repository owner. */
    owner: string,
    /** Name of repository. */
    repo: string,
    /** Is used to set specified media type. */
    accept?: string,
    /** Custom blob (should be imported from models) */
    body: models.Blob,
  };

  /**
   * Create a custom Blob.
   * Response generated for [ 201 ] HTTP response code.
   */
  postReposOwnerRepoGitBlobs(
    args: Exclude<APIClientInterface['postReposOwnerRepoGitBlobsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Blob[]>;
  postReposOwnerRepoGitBlobs(
    args: Exclude<APIClientInterface['postReposOwnerRepoGitBlobsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Blob[]>>;
  postReposOwnerRepoGitBlobs(
    args: Exclude<APIClientInterface['postReposOwnerRepoGitBlobsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Blob[]>>;

  /**
   * Arguments object for method `getReposOwnerRepoGitBlobsShaCode`.
   */
  getReposOwnerRepoGitBlobsShaCodeParams?: {
    /** Name of repository owner. */
    owner: string,
    /** Name of repository. */
    repo: string,
    /** SHA-1 code. */
    shaCode: string,
    /** Is used to set specified media type. */
    accept?: string,
  };

  /**
   * Get standard File
   * Response generated for [ 200 ] HTTP response code.
   */
  getReposOwnerRepoGitBlobsShaCode(
    args: Exclude<APIClientInterface['getReposOwnerRepoGitBlobsShaCodeParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<File>;
  getReposOwnerRepoGitBlobsShaCode(
    args: Exclude<APIClientInterface['getReposOwnerRepoGitBlobsShaCodeParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<File>>;
  getReposOwnerRepoGitBlobsShaCode(
    args: Exclude<APIClientInterface['getReposOwnerRepoGitBlobsShaCodeParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<File>>;

}
