/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpClient } from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { DefaultHttpOptions, HttpOptions } from '../../types';
import { USE_DOMAIN, USE_HTTP_OPTIONS, ProjectAPIClient } from './project-api-client.service';
import { ProjectAPIClientInterface } from './project-api-client.interface';

import * as models from '../../models';
import * as guards from '../../guards';

@Injectable()
export class GuardedProjectAPIClient extends ProjectAPIClient implements ProjectAPIClientInterface {

  constructor(readonly httpClient: HttpClient,
              @Optional() @Inject(USE_DOMAIN) domain?: string,
              @Optional() @Inject(USE_HTTP_OPTIONS) options?: DefaultHttpOptions) {
    super(httpClient, domain, options);
  }

  getProjectTypes(
    requestHttpOptions?: HttpOptions
  ): Observable<models.ProjectTypeViewModel[]> {
    return super.getProjectTypes(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isProjectTypeViewModel(item)) ) || console.error(`TypeGuard for response 'models.ProjectTypeViewModel[]' caught inconsistency.`, res)));
  }

}
