/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * - error format
 * - 1 V1
 * - 2 V2
 * 
 */
export enum NumberEnumParam {
  V1 = 1,
  V2 = 2,
}
