/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * - 1 First
 * - 2 Second
 * - 3 Third
 * 
 */
export enum Position {
  First = 1,
  Second = 2,
  Third = 3,
}
