pipeline:
  build-master:
    image: node
    when:
      event: push
      branch: master
    commands:
      - npm ci
      - npm run lint
      - npm run test
      - npm run build
  build-pr:
    image: node
    when:
      event: pr
    commands:
      - npm ci
      - npm run lint
      - npm run test
      - npm run build
  release:
    when:
      event: tag
    image: plugins/npm
    username: flowup
    email: hello@flowup.cz
    secrets: [npm_password]
