/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import {
  Criticality,
  ImportStatusDetailsItem,
} from '.';

export interface ImportStatusItem {
  criticality?: Criticality;
  details?: ImportStatusDetailsItem[];
  dueDate?: string;
  id?: number;
  issues?: number;
  progress?: number;
  title?: string;
}
