/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * - 1 ThirdParty
 * - 2 File
 * 
 */
export enum ImportType {
  ThirdParty = 1,
  File = 2,
}
