/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export interface PasswordCreationPolicies {
  passwordMinChars?: number;
  passwordMinDigits?: number;
  passwordMinLength?: number;
  passwordMinSpecialChars?: number;
  passwordMinUpperChars?: number;
  passwordNotMatchPrevious?: number;
  passwordResetLinkExpiration?: number;
  preventOldPasswordReuse?: boolean;
}
