/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * - 1 Year
 * - 2 Month
 * - 3 Week
 * 
 */
export enum Period {
  Year = 1,
  Month = 2,
  Week = 3,
}
