/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * - 1 Pending
 * - 2 InProgress
 * - 3 Complete
 * 
 */
export enum Status {
  Pending = 1,
  InProgress = 2,
  Complete = 3,
}
