/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * - 1 Active
 * - 2 Blocked
 * 
 */
export enum UserStatus {
  Active = 1,
  Blocked = 2,
}
