/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpClient } from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { DefaultHttpOptions, HttpOptions } from '../../types';
import { USE_DOMAIN, USE_HTTP_OPTIONS, FeedsAPIClient } from './feeds-api-client.service';
import { FeedsAPIClientInterface } from './feeds-api-client.interface';

import * as models from '../../models';
import * as guards from '../../guards';

@Injectable()
export class GuardedFeedsAPIClient extends FeedsAPIClient implements FeedsAPIClientInterface {

  constructor(readonly httpClient: HttpClient,
              @Optional() @Inject(USE_DOMAIN) domain?: string,
              @Optional() @Inject(USE_HTTP_OPTIONS) options?: DefaultHttpOptions) {
    super(httpClient, domain, options);
  }

  getFeeds(
    args: Exclude<FeedsAPIClientInterface['getFeedsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.Feeds> {
    return super.getFeeds(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isFeeds(res) || console.error(`TypeGuard for response 'models.Feeds' caught inconsistency.`, res)));
  }

}
