/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpResponse, HttpEvent } from '@angular/common/http';
import { Observable } from 'rxjs';import { HttpOptions } from './types';

import * as models from './models';
export interface APIClientInterface {
  /**
   * Arguments object for method `auth`.
   */
  authParams?: {
    /** Structure entity object that needs to be added */
    body: models.AuthForm,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  auth(
    args: Exclude<APIClientInterface['authParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  auth(
    args: Exclude<APIClientInterface['authParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  auth(
    args: Exclude<APIClientInterface['authParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  authRef(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  authRef(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  authRef(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `passwordRestoreRequest`.
   */
  passwordRestoreRequestParams?: {
    /** Structure entity object that needs to be added */
    body: models.RestoreForm,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  passwordRestoreRequest(
    args: Exclude<APIClientInterface['passwordRestoreRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  passwordRestoreRequest(
    args: Exclude<APIClientInterface['passwordRestoreRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  passwordRestoreRequest(
    args: Exclude<APIClientInterface['passwordRestoreRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `passwordRestoreEmailRequest`.
   */
  passwordRestoreEmailRequestParams?: {
    /** Structure entity object that needs to be added */
    body: models.RestoreRequestForm,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  passwordRestoreEmailRequest(
    args: Exclude<APIClientInterface['passwordRestoreEmailRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  passwordRestoreEmailRequest(
    args: Exclude<APIClientInterface['passwordRestoreEmailRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  passwordRestoreEmailRequest(
    args: Exclude<APIClientInterface['passwordRestoreEmailRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `passwordRestoreCheckRestoreGuid`.
   */
  passwordRestoreCheckRestoreGuidParams?: {
    /** RestoreGuid for check */
    restoreGuid: string,
  };

  /**
   * Response generated for [ 200 ] HTTP response code.
   */
  passwordRestoreCheckRestoreGuid(
    args: Exclude<APIClientInterface['passwordRestoreCheckRestoreGuidParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  passwordRestoreCheckRestoreGuid(
    args: Exclude<APIClientInterface['passwordRestoreCheckRestoreGuidParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  passwordRestoreCheckRestoreGuid(
    args: Exclude<APIClientInterface['passwordRestoreCheckRestoreGuidParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Get list of roles to permissions mapping
   * Response generated for [ 200 ] HTTP response code.
   */
  getAclList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.AclItem[]>;
  getAclList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.AclItem[]>>;
  getAclList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.AclItem[]>>;

  /**
   * Get structure entities list
   * Response generated for [ 200 ] HTTP response code.
   */
  getStructureEntitiesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Structure[]>;
  getStructureEntitiesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Structure[]>>;
  getStructureEntitiesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Structure[]>>;

  /**
   * Arguments object for method `addStructureEntity`.
   */
  addStructureEntityParams?: {
    /** Structure entity object that needs to be added */
    body: models.StructureAddParameters,
  };

  /**
   * Add a new structure entity
   * Response generated for [ 200 ] HTTP response code.
   */
  addStructureEntity(
    args: Exclude<APIClientInterface['addStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Structure>;
  addStructureEntity(
    args: Exclude<APIClientInterface['addStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Structure>>;
  addStructureEntity(
    args: Exclude<APIClientInterface['addStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Structure>>;

  /**
   * Arguments object for method `updateStructureEntity`.
   */
  updateStructureEntityParams?: {
    /** structure id to update */
    structureId: number,
    /** Structure entity object that needs to be updated */
    body: models.StructureForm,
  };

  /**
   * Update an existing structure entity
   * Response generated for [ 200 ] HTTP response code.
   */
  updateStructureEntity(
    args: Exclude<APIClientInterface['updateStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Structure>;
  updateStructureEntity(
    args: Exclude<APIClientInterface['updateStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Structure>>;
  updateStructureEntity(
    args: Exclude<APIClientInterface['updateStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Structure>>;

  /**
   * Arguments object for method `deleteStructureEntity`.
   */
  deleteStructureEntityParams?: {
    /** structure id to delete */
    structureId: number,
  };

  /**
   * Deletes a structure entity
   * Response generated for [ 200 ] HTTP response code.
   */
  deleteStructureEntity(
    args: Exclude<APIClientInterface['deleteStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deleteStructureEntity(
    args: Exclude<APIClientInterface['deleteStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deleteStructureEntity(
    args: Exclude<APIClientInterface['deleteStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `getReportsList`.
   */
  getReportsListParams?: {
    /**
     * - 1 Pending
     * - 2 InProgress
     * - 3 Complete
     * 
     */
    status?: models.Status,
    pageSize: number,
    /** page number */
    page: number,
    /** id | title | subtitle | criticality | status | issues | deadline */
    orderBy: ('id' | 'title' | 'subtitle' | 'criticality' | 'status' | 'issues' | 'deadline'),
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
  };

  /**
   * Get reports list
   * [Screenshot from design](http://prntscr.com/hy4z8d)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getReportsList(
    args: Exclude<APIClientInterface['getReportsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getReportsList(
    args: Exclude<APIClientInterface['getReportsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getReportsList(
    args: Exclude<APIClientInterface['getReportsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `getReportDetails`.
   */
  getReportDetailsParams?: {
    /** report id to get */
    id: number,
  };

  /**
   * Get report details
   * [Screenshot from design](http://prntscr.com/hywkd5)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getReportDetails(
    args: Exclude<APIClientInterface['getReportDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.ReportItem[]>;
  getReportDetails(
    args: Exclude<APIClientInterface['getReportDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.ReportItem[]>>;
  getReportDetails(
    args: Exclude<APIClientInterface['getReportDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.ReportItem[]>>;

  /**
   * Arguments object for method `getReportPreview`.
   */
  getReportPreviewParams?: {
    /**
     * [See #/definitions/ReportTemplate](#/Data_Import/getReportDetails)
     * 
     */
    templateId: number,
    pageSize: number,
    /** page number */
    page: number,
    /** column id */
    orderBy?: number,
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
  };

  /**
   * Get report preview
   * [Screenshot from design](http://prntscr.com/i3z8zb)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getReportPreview(
    args: Exclude<APIClientInterface['getReportPreviewParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getReportPreview(
    args: Exclude<APIClientInterface['getReportPreviewParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getReportPreview(
    args: Exclude<APIClientInterface['getReportPreviewParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `getImportHistory`.
   */
  getImportHistoryParams?: {
    /**
     * [See #/definitions/ReportTemplate](#/Data_Import/getReportDetails)
     * 
     */
    templateId: number,
  };

  /**
   * Get import history
   * [Screenshot from design](http://prntscr.com/i3ym4j)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getImportHistory(
    args: Exclude<APIClientInterface['getImportHistoryParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.ImportHistoryItem[]>;
  getImportHistory(
    args: Exclude<APIClientInterface['getImportHistoryParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.ImportHistoryItem[]>>;
  getImportHistory(
    args: Exclude<APIClientInterface['getImportHistoryParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.ImportHistoryItem[]>>;

  /**
   * Arguments object for method `uploadFile`.
   */
  uploadFileParams?: {
    /**
     * [See #/definitions/ReportTemplate](#/Data_Import/getReportDetails)
     * 
     */
    templateId: number,
    /** file to upload */
    file: File,
  };

  /**
   * Upload a completed template
   * [Screenshot from design](http://prntscr.com/hy521p)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<number>;
  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<number>>;
  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<number>>;

  /**
   * Arguments object for method `listTemplateColumns`.
   */
  listTemplateColumnsParams?: {
    /**
     * [See #/definitions/ReportTemplate](#/Data_Import/getReportDetails)
     * 
     */
    templateId: number,
  };

  /**
   * Get list of current Import template columns
   * [Screenshot from design](http://prntscr.com/hy52hi)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  listTemplateColumns(
    args: Exclude<APIClientInterface['listTemplateColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Column[]>;
  listTemplateColumns(
    args: Exclude<APIClientInterface['listTemplateColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Column[]>>;
  listTemplateColumns(
    args: Exclude<APIClientInterface['listTemplateColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Column[]>>;

  /**
   * Arguments object for method `listReportColumns`.
   */
  listReportColumnsParams?: {
    /** Id of current import */
    id: number,
  };

  /**
   * Get list of current Import template columns
   * [Screenshot from design](http://prntscr.com/hy52zr)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  listReportColumns(
    args: Exclude<APIClientInterface['listReportColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Column[]>;
  listReportColumns(
    args: Exclude<APIClientInterface['listReportColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Column[]>>;
  listReportColumns(
    args: Exclude<APIClientInterface['listReportColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Column[]>>;

  /**
   * Arguments object for method `saveColumnsMapping`.
   */
  saveColumnsMappingParams?: {
    /** Id of current import */
    id: number,
    /** Column mappint for current import */
    body: models.ColumnMapping[],
  };

  /**
   * Save columns mapping
   * [Screenshot from design](http://prntscr.com/hy53jt)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  saveColumnsMapping(
    args: Exclude<APIClientInterface['saveColumnsMappingParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Table>;
  saveColumnsMapping(
    args: Exclude<APIClientInterface['saveColumnsMappingParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Table>>;
  saveColumnsMapping(
    args: Exclude<APIClientInterface['saveColumnsMappingParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Table>>;

  /**
   * Arguments object for method `getValidationTable`.
   */
  getValidationTableParams?: {
    /** Id of current import */
    id: number,
  };

  /**
   * Get validation table
   * [Screenshot from design](http://prntscr.com/hy5fct)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getValidationTable(
    args: Exclude<APIClientInterface['getValidationTableParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.ValidatedTable>;
  getValidationTable(
    args: Exclude<APIClientInterface['getValidationTableParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.ValidatedTable>>;
  getValidationTable(
    args: Exclude<APIClientInterface['getValidationTableParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.ValidatedTable>>;

  /**
   * Arguments object for method `downloadImportedFile`.
   */
  downloadImportedFileParams?: {
    /** Id of current import */
    id: number,
    /** Indicator of downloading data(all or errors only) */
    all?: boolean,
  };

  /**
   * Download imported data
   * [Screenshot from design](http://prntscr.com/hy55ga)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  downloadImportedFile(
    args: Exclude<APIClientInterface['downloadImportedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<File>;
  downloadImportedFile(
    args: Exclude<APIClientInterface['downloadImportedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<File>>;
  downloadImportedFile(
    args: Exclude<APIClientInterface['downloadImportedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<File>>;

  /**
   * Arguments object for method `importConfirmation`.
   */
  importConfirmationParams?: {
    /** Id of current import */
    id: number,
  };

  /**
   * Confirm final import
   * [Screenshot from design](http://prntscr.com/hy57nj)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  importConfirmation(
    args: Exclude<APIClientInterface['importConfirmationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.ImportResponse>;
  importConfirmation(
    args: Exclude<APIClientInterface['importConfirmationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.ImportResponse>>;
  importConfirmation(
    args: Exclude<APIClientInterface['importConfirmationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.ImportResponse>>;

  /**
   * Arguments object for method `downloadImportOriginalFile`.
   */
  downloadImportOriginalFileParams?: {
    /** Id of current import */
    id: number,
  };

  /**
   * Download original file
   * [Screenshot from design](http://prntscr.com/hy5a54)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  downloadImportOriginalFile(
    args: Exclude<APIClientInterface['downloadImportOriginalFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<File>;
  downloadImportOriginalFile(
    args: Exclude<APIClientInterface['downloadImportOriginalFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<File>>;
  downloadImportOriginalFile(
    args: Exclude<APIClientInterface['downloadImportOriginalFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<File>>;

  /**
   * Arguments object for method `downloadImportSkippedFile`.
   */
  downloadImportSkippedFileParams?: {
    /** Id of current import */
    id: number,
  };

  /**
   * Download skipped rows file
   * [Screenshot from design](http://prntscr.com/hy5ae7)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  downloadImportSkippedFile(
    args: Exclude<APIClientInterface['downloadImportSkippedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<File>;
  downloadImportSkippedFile(
    args: Exclude<APIClientInterface['downloadImportSkippedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<File>>;
  downloadImportSkippedFile(
    args: Exclude<APIClientInterface['downloadImportSkippedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<File>>;

  /**
   * Arguments object for method `cancelImport`.
   */
  cancelImportParams?: {
    /** Id of current import */
    id: number,
  };

  /**
   * Cancel current import
   * [Screenshot from design](http://prntscr.com/hy5aqq)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  cancelImport(
    args: Exclude<APIClientInterface['cancelImportParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  cancelImport(
    args: Exclude<APIClientInterface['cancelImportParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  cancelImport(
    args: Exclude<APIClientInterface['cancelImportParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `overrideImport`.
   */
  overrideImportParams?: {
    /** Id of current import */
    id: number,
    /** description of override request */
    description: string,
    /** file to upload */
    file: File,
  };

  /**
   * Request override data for import
   * [Screenshot from design](http://prntscr.com/hy5bi6)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  overrideImport(
    args: Exclude<APIClientInterface['overrideImportParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  overrideImport(
    args: Exclude<APIClientInterface['overrideImportParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  overrideImport(
    args: Exclude<APIClientInterface['overrideImportParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `geImportStats`.
   */
  geImportStatsParams?: {
    /**
     * - 1 Year
     * - 2 Month
     * - 3 Week
     * 
     */
    period?: models.Period,
  };

  /**
   * Get import stats
   * [Screenshot from design](http://prntscr.com/i4052r)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  geImportStats(
    args?: APIClientInterface['geImportStatsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.TotalImportStats>;
  geImportStats(
    args?: APIClientInterface['geImportStatsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.TotalImportStats>>;
  geImportStats(
    args?: APIClientInterface['geImportStatsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.TotalImportStats>>;

  /**
   * Arguments object for method `getIssuesList`.
   */
  getIssuesListParams?: {
    /**
     * - 1 Year
     * - 2 Month
     * - 3 Week
     * 
     */
    period?: models.Period,
    /**
     * - 1 Pending
     * - 2 Resolved
     * 
     */
    status?: models.IssueStatus,
    pageSize: number,
    /** page number */
    page: number,
    /** name | school | dueDate | alert */
    orderBy: ('name' | 'school' | 'dueDate' | 'alert'),
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
  };

  /**
   * Get issues list
   * [Screenshot from design](http://prntscr.com/i40s18)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getIssuesList(
    args: Exclude<APIClientInterface['getIssuesListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getIssuesList(
    args: Exclude<APIClientInterface['getIssuesListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getIssuesList(
    args: Exclude<APIClientInterface['getIssuesListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `getStatusesList`.
   */
  getStatusesListParams?: {
    /**
     * - 1 Year
     * - 2 Month
     * - 3 Week
     * 
     */
    period?: models.Period,
    /**
     * - 1 Live
     * - 2 PastDeadline
     * 
     */
    status?: models.ImportStatus,
    pageSize: number,
    /** page number */
    page: number,
    /** name | issues | dueDate | progress */
    orderBy: ('name' | 'issues' | 'dueDate' | 'progress'),
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
  };

  /**
   * Get import statuses list
   * [Screenshot from design](http://prntscr.com/i4byyx)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getStatusesList(
    args: Exclude<APIClientInterface['getStatusesListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getStatusesList(
    args: Exclude<APIClientInterface['getStatusesListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getStatusesList(
    args: Exclude<APIClientInterface['getStatusesListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `getUsersList`.
   */
  getUsersListParams?: {
    /**
     * - 1 Year
     * - 2 Month
     * - 3 Week
     * 
     */
    period?: models.Period,
    /**
     * - 1 Live
     * - 2 PastDeadline
     * 
     */
    status?: models.ImportStatus,
    pageSize: number,
    /** page number */
    page: number,
    /** name | issues | dueDate | progress */
    orderBy: ('name' | 'issues' | 'dueDate' | 'progress'),
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
    /** role id | [Screenshot from design](http://prntscr.com/ib9yal) */
    assignedToRole?: number,
    /** role id | [Screenshot from design](http://prntscr.com/ib9z16) */
    unassignedFromRole?: number,
  };

  /**
   * Get users list
   * Response generated for [ 200 ] HTTP response code.
   */
  getUsersList(
    args: Exclude<APIClientInterface['getUsersListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getUsersList(
    args: Exclude<APIClientInterface['getUsersListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getUsersList(
    args: Exclude<APIClientInterface['getUsersListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `createUser`.
   */
  createUserParams?: {
    /** User entity object that needs to be added */
    body: models.UserDetails,
  };

  /**
   * Create user
   * Response generated for [ 200 ] HTTP response code.
   */
  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.UserDetails>;
  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.UserDetails>>;
  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.UserDetails>>;

  /**
   * Get acl structure
   * Response generated for [ 200 ] HTTP response code.
   */
  getAclStructure(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Acl[]>;
  getAclStructure(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Acl[]>>;
  getAclStructure(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Acl[]>>;

  /**
   * Arguments object for method `getUserDetails`.
   */
  getUserDetailsParams?: {
    id: number,
  };

  /**
   * getUserDetails
   * Response generated for [ 200 ] HTTP response code.
   */
  getUserDetails(
    args: Exclude<APIClientInterface['getUserDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.UserDetails[]>;
  getUserDetails(
    args: Exclude<APIClientInterface['getUserDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.UserDetails[]>>;
  getUserDetails(
    args: Exclude<APIClientInterface['getUserDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.UserDetails[]>>;

  /**
   * Arguments object for method `updateUser`.
   */
  updateUserParams?: {
    id: number,
    /** User entity object that needs to be updated */
    body: models.UserDetails,
  };

  /**
   * update user by id
   * Response generated for [ 200 ] HTTP response code.
   */
  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.UserDetails>;
  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.UserDetails>>;
  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.UserDetails>>;

  /**
   * Arguments object for method `deleteUser`.
   */
  deleteUserParams?: {
    id: number,
  };

  /**
   * delete user by id
   * Response generated for [ 200 ] HTTP response code.
   */
  deleteUser(
    args: Exclude<APIClientInterface['deleteUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deleteUser(
    args: Exclude<APIClientInterface['deleteUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deleteUser(
    args: Exclude<APIClientInterface['deleteUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Get roles list
   * [Screenshot from design](http://prntscr.com/i93q0s)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getRolesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.RoleListItem[]>;
  getRolesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.RoleListItem[]>>;
  getRolesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.RoleListItem[]>>;

  /**
   * Arguments object for method `createRole`.
   */
  createRoleParams?: {
    /** Role entity object that needs to be added */
    body: object,
  };

  /**
   * Create role
   * Response generated for [ 200 ] HTTP response code.
   */
  createRole(
    args: Exclude<APIClientInterface['createRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.RoleDetailsItem>;
  createRole(
    args: Exclude<APIClientInterface['createRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.RoleDetailsItem>>;
  createRole(
    args: Exclude<APIClientInterface['createRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.RoleDetailsItem>>;

  /**
   * Get privileges list
   * [Screenshot from design](http://prntscr.com/i947a3)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.PrivilegeTreeItem[]>;
  getList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.PrivilegeTreeItem[]>>;
  getList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.PrivilegeTreeItem[]>>;

  /**
   * Arguments object for method `getRoleDetails`.
   */
  getRoleDetailsParams?: {
    id: number,
  };

  /**
   * Get role details
   * Response generated for [ 200 ] HTTP response code.
   */
  getRoleDetails(
    args: Exclude<APIClientInterface['getRoleDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.RoleDetailsItem[]>;
  getRoleDetails(
    args: Exclude<APIClientInterface['getRoleDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.RoleDetailsItem[]>>;
  getRoleDetails(
    args: Exclude<APIClientInterface['getRoleDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.RoleDetailsItem[]>>;

  /**
   * Arguments object for method `updateRole`.
   */
  updateRoleParams?: {
    id: number,
    body?: models.RoleUpdateDetails,
  };

  /**
   * Update role by id
   * Response generated for [ 200 ] HTTP response code.
   */
  updateRole(
    args: Exclude<APIClientInterface['updateRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.RoleDetailsItem>;
  updateRole(
    args: Exclude<APIClientInterface['updateRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.RoleDetailsItem>>;
  updateRole(
    args: Exclude<APIClientInterface['updateRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.RoleDetailsItem>>;

  /**
   * Arguments object for method `deleteRole`.
   */
  deleteRoleParams?: {
    id: number,
  };

  /**
   * Ddelete role by id
   * Response generated for [ 200 ] HTTP response code.
   */
  deleteRole(
    args: Exclude<APIClientInterface['deleteRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deleteRole(
    args: Exclude<APIClientInterface['deleteRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deleteRole(
    args: Exclude<APIClientInterface['deleteRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Get unviewed notifications list
   * [Screenshot from design](http://prntscr.com/iba7xr)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getNewNotificationsList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.NotificationListItem[]>;
  getNewNotificationsList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.NotificationListItem[]>>;
  getNewNotificationsList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.NotificationListItem[]>>;

  /**
   * Arguments object for method `markViewedNotifications`.
   */
  markViewedNotificationsParams?: {
    body?: number[],
  };

  /**
   * Mark notifications as viewed
   * Response generated for [ 200 ] HTTP response code.
   */
  markViewedNotifications(
    args?: APIClientInterface['markViewedNotificationsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  markViewedNotifications(
    args?: APIClientInterface['markViewedNotificationsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  markViewedNotifications(
    args?: APIClientInterface['markViewedNotificationsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `getNotificationsList`.
   */
  getNotificationsListParams?: {
    pageSize: number,
    /** page number */
    page: number,
    /** name | description | priority | date */
    orderBy: ('name' | 'description' | 'priority' | 'date'),
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
  };

  /**
   * Get user's notifications list
   * [Screenshot from design](http://prntscr.com/iba8tq)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getNotificationsList(
    args: Exclude<APIClientInterface['getNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getNotificationsList(
    args: Exclude<APIClientInterface['getNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getNotificationsList(
    args: Exclude<APIClientInterface['getNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Get modules list
   * [Screenshot from design](http://prntscr.com/ibac47) |
   * [Screenshot from design](http://prntscr.com/ibacgu)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getModulesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.NotificationModule[]>;
  getModulesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.NotificationModule[]>>;
  getModulesList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.NotificationModule[]>>;

  /**
   * Get triggers list
   * [Screenshot from design](http://prntscr.com/ibad9m)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getTriggersList(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.NotificationTrigger[]>;
  getTriggersList(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.NotificationTrigger[]>>;
  getTriggersList(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.NotificationTrigger[]>>;

  /**
   * Arguments object for method `getModuleNotificationsList`.
   */
  getModuleNotificationsListParams?: {
    moduleId: number,
    pageSize: number,
    /** page number */
    page: number,
    /** name | description | priority | date */
    orderBy: ('name' | 'description' | 'priority' | 'date'),
    /**
     * - asc
     * - desc
     * 
     */
    order?: models.Order,
  };

  /**
   * Get module's notifications list
   * [Screenshot from design](http://prntscr.com/iba8tq)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getModuleNotificationsList(
    args: Exclude<APIClientInterface['getModuleNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<object>;
  getModuleNotificationsList(
    args: Exclude<APIClientInterface['getModuleNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<object>>;
  getModuleNotificationsList(
    args: Exclude<APIClientInterface['getModuleNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<object>>;

  /**
   * Arguments object for method `enableNotification`.
   */
  enableNotificationParams?: {
    id: number,
  };

  /**
   * Enable notification
   * Response generated for [ 200 ] HTTP response code.
   */
  enableNotification(
    args: Exclude<APIClientInterface['enableNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  enableNotification(
    args: Exclude<APIClientInterface['enableNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  enableNotification(
    args: Exclude<APIClientInterface['enableNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `disableNotification`.
   */
  disableNotificationParams?: {
    id: number,
  };

  /**
   * Disable notification
   * Response generated for [ 200 ] HTTP response code.
   */
  disableNotification(
    args: Exclude<APIClientInterface['disableNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  disableNotification(
    args: Exclude<APIClientInterface['disableNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  disableNotification(
    args: Exclude<APIClientInterface['disableNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `getNotification`.
   */
  getNotificationParams?: {
    id: number,
  };

  /**
   * Get notification details
   * Response generated for [ 200 ] HTTP response code.
   */
  getNotification(
    args: Exclude<APIClientInterface['getNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.NotificationEditableListItem>;
  getNotification(
    args: Exclude<APIClientInterface['getNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.NotificationEditableListItem>>;
  getNotification(
    args: Exclude<APIClientInterface['getNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.NotificationEditableListItem>>;

  /**
   * Arguments object for method `updateNotification`.
   */
  updateNotificationParams?: {
    id: number,
    body?: models.NotificationEditable,
  };

  /**
   * Update notification
   * Response generated for [ 200 ] HTTP response code.
   */
  updateNotification(
    args: Exclude<APIClientInterface['updateNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  updateNotification(
    args: Exclude<APIClientInterface['updateNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  updateNotification(
    args: Exclude<APIClientInterface['updateNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `createNotification`.
   */
  createNotificationParams?: {
    body?: models.NotificationEditable,
  };

  /**
   * Create notification
   * Response generated for [ 200 ] HTTP response code.
   */
  createNotification(
    args?: APIClientInterface['createNotificationParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<number>;
  createNotification(
    args?: APIClientInterface['createNotificationParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<number>>;
  createNotification(
    args?: APIClientInterface['createNotificationParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<number>>;

  /**
   * Get password verefication settings
   * [Screenshot from design](http://prntscr.com/ijzt2b)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getPassVerificationPolicies(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.PasswordVerificationPolicies>;
  getPassVerificationPolicies(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.PasswordVerificationPolicies>>;
  getPassVerificationPolicies(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.PasswordVerificationPolicies>>;

  /**
   * Arguments object for method `udatePassVerificationPolicies`.
   */
  udatePassVerificationPoliciesParams?: {
    body?: models.PasswordVerificationPolicies,
  };

  /**
   * Update password verefication settings
   * [Screenshot from design](http://prntscr.com/ijzt2b)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  udatePassVerificationPolicies(
    args?: APIClientInterface['udatePassVerificationPoliciesParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.PasswordVerificationPolicies>;
  udatePassVerificationPolicies(
    args?: APIClientInterface['udatePassVerificationPoliciesParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.PasswordVerificationPolicies>>;
  udatePassVerificationPolicies(
    args?: APIClientInterface['udatePassVerificationPoliciesParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.PasswordVerificationPolicies>>;

  /**
   * Get password creation settings
   * [Screenshot from design](http://prntscr.com/ijzuv3)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getPassCreationPolicies(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.PasswordCreationPolicies>;
  getPassCreationPolicies(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.PasswordCreationPolicies>>;
  getPassCreationPolicies(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.PasswordCreationPolicies>>;

  /**
   * Arguments object for method `udatePassCreationPolicies`.
   */
  udatePassCreationPoliciesParams?: {
    body?: models.PasswordCreationPolicies,
  };

  /**
   * Update password creation settings
   * [Screenshot from design](http://prntscr.com/ijzuv3)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  udatePassCreationPolicies(
    args?: APIClientInterface['udatePassCreationPoliciesParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.PasswordCreationPolicies>;
  udatePassCreationPolicies(
    args?: APIClientInterface['udatePassCreationPoliciesParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.PasswordCreationPolicies>>;
  udatePassCreationPolicies(
    args?: APIClientInterface['udatePassCreationPoliciesParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.PasswordCreationPolicies>>;

  /**
   * Get other security settings settings
   * [Screenshot from design](http://prntscr.com/ijzvo3)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  getOtherSecuritySettings(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.OtherSecuritySettings>;
  getOtherSecuritySettings(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.OtherSecuritySettings>>;
  getOtherSecuritySettings(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.OtherSecuritySettings>>;

  /**
   * Arguments object for method `udateOtherSecuritySettings`.
   */
  udateOtherSecuritySettingsParams?: {
    body?: models.OtherSecuritySettings,
  };

  /**
   * Update other security settings settings
   * [Screenshot from design](http://prntscr.com/ijzvo3)
   * 
   * Response generated for [ 200 ] HTTP response code.
   */
  udateOtherSecuritySettings(
    args?: APIClientInterface['udateOtherSecuritySettingsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.OtherSecuritySettings>;
  udateOtherSecuritySettings(
    args?: APIClientInterface['udateOtherSecuritySettingsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.OtherSecuritySettings>>;
  udateOtherSecuritySettings(
    args?: APIClientInterface['udateOtherSecuritySettingsParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.OtherSecuritySettings>>;

}
