/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpClient } from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { DefaultHttpOptions, HttpOptions } from './types';
import { USE_DOMAIN, USE_HTTP_OPTIONS, APIClient } from './api-client.service';
import { APIClientInterface } from './api-client.interface';

import * as models from './models';
import * as guards from './guards';

@Injectable()
export class GuardedAPIClient extends APIClient implements APIClientInterface {

  constructor(readonly httpClient: HttpClient,
              @Optional() @Inject(USE_DOMAIN) domain?: string,
              @Optional() @Inject(USE_HTTP_OPTIONS) options?: DefaultHttpOptions) {
    super(httpClient, domain, options);
  }

  auth(
    args: Exclude<APIClientInterface['authParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.auth(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  authRef(
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.authRef(requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  passwordRestoreRequest(
    args: Exclude<APIClientInterface['passwordRestoreRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.passwordRestoreRequest(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  passwordRestoreEmailRequest(
    args: Exclude<APIClientInterface['passwordRestoreEmailRequestParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.passwordRestoreEmailRequest(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  passwordRestoreCheckRestoreGuid(
    args: Exclude<APIClientInterface['passwordRestoreCheckRestoreGuidParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.passwordRestoreCheckRestoreGuid(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getAclList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.AclItem[]> {
    return super.getAclList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isAclItem(item)) ) || console.error(`TypeGuard for response 'models.AclItem[]' caught inconsistency.`, res)));
  }

  getStructureEntitiesList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.Structure[]> {
    return super.getStructureEntitiesList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isStructure(item)) ) || console.error(`TypeGuard for response 'models.Structure[]' caught inconsistency.`, res)));
  }

  addStructureEntity(
    args: Exclude<APIClientInterface['addStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.Structure> {
    return super.addStructureEntity(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isStructure(res) || console.error(`TypeGuard for response 'models.Structure' caught inconsistency.`, res)));
  }

  updateStructureEntity(
    args: Exclude<APIClientInterface['updateStructureEntityParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.Structure> {
    return super.updateStructureEntity(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isStructure(res) || console.error(`TypeGuard for response 'models.Structure' caught inconsistency.`, res)));
  }

  getReportsList(
    args: Exclude<APIClientInterface['getReportsListParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getReportsList(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getReportDetails(
    args: Exclude<APIClientInterface['getReportDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.ReportItem[]> {
    return super.getReportDetails(args, requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isReportItem(item)) ) || console.error(`TypeGuard for response 'models.ReportItem[]' caught inconsistency.`, res)));
  }

  getReportPreview(
    args: Exclude<APIClientInterface['getReportPreviewParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getReportPreview(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getImportHistory(
    args: Exclude<APIClientInterface['getImportHistoryParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.ImportHistoryItem[]> {
    return super.getImportHistory(args, requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isImportHistoryItem(item)) ) || console.error(`TypeGuard for response 'models.ImportHistoryItem[]' caught inconsistency.`, res)));
  }

  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<number> {
    return super.uploadFile(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'number' || console.error(`TypeGuard for response 'number' caught inconsistency.`, res)));
  }

  listTemplateColumns(
    args: Exclude<APIClientInterface['listTemplateColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.Column[]> {
    return super.listTemplateColumns(args, requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isColumn(item)) ) || console.error(`TypeGuard for response 'models.Column[]' caught inconsistency.`, res)));
  }

  listReportColumns(
    args: Exclude<APIClientInterface['listReportColumnsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.Column[]> {
    return super.listReportColumns(args, requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isColumn(item)) ) || console.error(`TypeGuard for response 'models.Column[]' caught inconsistency.`, res)));
  }

  saveColumnsMapping(
    args: Exclude<APIClientInterface['saveColumnsMappingParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.Table> {
    return super.saveColumnsMapping(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isTable(res) || console.error(`TypeGuard for response 'models.Table' caught inconsistency.`, res)));
  }

  getValidationTable(
    args: Exclude<APIClientInterface['getValidationTableParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.ValidatedTable> {
    return super.getValidationTable(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isValidatedTable(res) || console.error(`TypeGuard for response 'models.ValidatedTable' caught inconsistency.`, res)));
  }

  downloadImportedFile(
    args: Exclude<APIClientInterface['downloadImportedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<File> {
    return super.downloadImportedFile(args, requestHttpOptions)
      .pipe(tap((res: any) => res instanceof File || console.error(`TypeGuard for response 'File' caught inconsistency.`, res)));
  }

  importConfirmation(
    args: Exclude<APIClientInterface['importConfirmationParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.ImportResponse> {
    return super.importConfirmation(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isImportResponse(res) || console.error(`TypeGuard for response 'models.ImportResponse' caught inconsistency.`, res)));
  }

  downloadImportOriginalFile(
    args: Exclude<APIClientInterface['downloadImportOriginalFileParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<File> {
    return super.downloadImportOriginalFile(args, requestHttpOptions)
      .pipe(tap((res: any) => res instanceof File || console.error(`TypeGuard for response 'File' caught inconsistency.`, res)));
  }

  downloadImportSkippedFile(
    args: Exclude<APIClientInterface['downloadImportSkippedFileParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<File> {
    return super.downloadImportSkippedFile(args, requestHttpOptions)
      .pipe(tap((res: any) => res instanceof File || console.error(`TypeGuard for response 'File' caught inconsistency.`, res)));
  }

  geImportStats(
    args: Exclude<APIClientInterface['geImportStatsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.TotalImportStats> {
    return super.geImportStats(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isTotalImportStats(res) || console.error(`TypeGuard for response 'models.TotalImportStats' caught inconsistency.`, res)));
  }

  getIssuesList(
    args: Exclude<APIClientInterface['getIssuesListParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getIssuesList(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getStatusesList(
    args: Exclude<APIClientInterface['getStatusesListParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getStatusesList(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getUsersList(
    args: Exclude<APIClientInterface['getUsersListParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getUsersList(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.UserDetails> {
    return super.createUser(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isUserDetails(res) || console.error(`TypeGuard for response 'models.UserDetails' caught inconsistency.`, res)));
  }

  getAclStructure(
    requestHttpOptions?: HttpOptions
  ): Observable<models.Acl[]> {
    return super.getAclStructure(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isAcl(item)) ) || console.error(`TypeGuard for response 'models.Acl[]' caught inconsistency.`, res)));
  }

  getUserDetails(
    args: Exclude<APIClientInterface['getUserDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.UserDetails[]> {
    return super.getUserDetails(args, requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isUserDetails(item)) ) || console.error(`TypeGuard for response 'models.UserDetails[]' caught inconsistency.`, res)));
  }

  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.UserDetails> {
    return super.updateUser(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isUserDetails(res) || console.error(`TypeGuard for response 'models.UserDetails' caught inconsistency.`, res)));
  }

  getRolesList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.RoleListItem[]> {
    return super.getRolesList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isRoleListItem(item)) ) || console.error(`TypeGuard for response 'models.RoleListItem[]' caught inconsistency.`, res)));
  }

  createRole(
    args: Exclude<APIClientInterface['createRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.RoleDetailsItem> {
    return super.createRole(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isRoleDetailsItem(res) || console.error(`TypeGuard for response 'models.RoleDetailsItem' caught inconsistency.`, res)));
  }

  getList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.PrivilegeTreeItem[]> {
    return super.getList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isPrivilegeTreeItem(item)) ) || console.error(`TypeGuard for response 'models.PrivilegeTreeItem[]' caught inconsistency.`, res)));
  }

  getRoleDetails(
    args: Exclude<APIClientInterface['getRoleDetailsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.RoleDetailsItem[]> {
    return super.getRoleDetails(args, requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isRoleDetailsItem(item)) ) || console.error(`TypeGuard for response 'models.RoleDetailsItem[]' caught inconsistency.`, res)));
  }

  updateRole(
    args: Exclude<APIClientInterface['updateRoleParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.RoleDetailsItem> {
    return super.updateRole(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isRoleDetailsItem(res) || console.error(`TypeGuard for response 'models.RoleDetailsItem' caught inconsistency.`, res)));
  }

  getNewNotificationsList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.NotificationListItem[]> {
    return super.getNewNotificationsList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isNotificationListItem(item)) ) || console.error(`TypeGuard for response 'models.NotificationListItem[]' caught inconsistency.`, res)));
  }

  getNotificationsList(
    args: Exclude<APIClientInterface['getNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getNotificationsList(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getModulesList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.NotificationModule[]> {
    return super.getModulesList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isNotificationModule(item)) ) || console.error(`TypeGuard for response 'models.NotificationModule[]' caught inconsistency.`, res)));
  }

  getTriggersList(
    requestHttpOptions?: HttpOptions
  ): Observable<models.NotificationTrigger[]> {
    return super.getTriggersList(requestHttpOptions)
      .pipe(tap((res: any) => ( Array.isArray(res) && res.every((item: any) => guards.isNotificationTrigger(item)) ) || console.error(`TypeGuard for response 'models.NotificationTrigger[]' caught inconsistency.`, res)));
  }

  getModuleNotificationsList(
    args: Exclude<APIClientInterface['getModuleNotificationsListParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<object> {
    return super.getModuleNotificationsList(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'object' || console.error(`TypeGuard for response 'object' caught inconsistency.`, res)));
  }

  getNotification(
    args: Exclude<APIClientInterface['getNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.NotificationEditableListItem> {
    return super.getNotification(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isNotificationEditableListItem(res) || console.error(`TypeGuard for response 'models.NotificationEditableListItem' caught inconsistency.`, res)));
  }

  createNotification(
    args: Exclude<APIClientInterface['createNotificationParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<number> {
    return super.createNotification(args, requestHttpOptions)
      .pipe(tap((res: any) => typeof res === 'number' || console.error(`TypeGuard for response 'number' caught inconsistency.`, res)));
  }

  getPassVerificationPolicies(
    requestHttpOptions?: HttpOptions
  ): Observable<models.PasswordVerificationPolicies> {
    return super.getPassVerificationPolicies(requestHttpOptions)
      .pipe(tap((res: any) => guards.isPasswordVerificationPolicies(res) || console.error(`TypeGuard for response 'models.PasswordVerificationPolicies' caught inconsistency.`, res)));
  }

  udatePassVerificationPolicies(
    args: Exclude<APIClientInterface['udatePassVerificationPoliciesParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.PasswordVerificationPolicies> {
    return super.udatePassVerificationPolicies(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isPasswordVerificationPolicies(res) || console.error(`TypeGuard for response 'models.PasswordVerificationPolicies' caught inconsistency.`, res)));
  }

  getPassCreationPolicies(
    requestHttpOptions?: HttpOptions
  ): Observable<models.PasswordCreationPolicies> {
    return super.getPassCreationPolicies(requestHttpOptions)
      .pipe(tap((res: any) => guards.isPasswordCreationPolicies(res) || console.error(`TypeGuard for response 'models.PasswordCreationPolicies' caught inconsistency.`, res)));
  }

  udatePassCreationPolicies(
    args: Exclude<APIClientInterface['udatePassCreationPoliciesParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.PasswordCreationPolicies> {
    return super.udatePassCreationPolicies(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isPasswordCreationPolicies(res) || console.error(`TypeGuard for response 'models.PasswordCreationPolicies' caught inconsistency.`, res)));
  }

  getOtherSecuritySettings(
    requestHttpOptions?: HttpOptions
  ): Observable<models.OtherSecuritySettings> {
    return super.getOtherSecuritySettings(requestHttpOptions)
      .pipe(tap((res: any) => guards.isOtherSecuritySettings(res) || console.error(`TypeGuard for response 'models.OtherSecuritySettings' caught inconsistency.`, res)));
  }

  udateOtherSecuritySettings(
    args: Exclude<APIClientInterface['udateOtherSecuritySettingsParams'], undefined>,
    requestHttpOptions?: HttpOptions
  ): Observable<models.OtherSecuritySettings> {
    return super.udateOtherSecuritySettings(args, requestHttpOptions)
      .pipe(tap((res: any) => guards.isOtherSecuritySettings(res) || console.error(`TypeGuard for response 'models.OtherSecuritySettings' caught inconsistency.`, res)));
  }

}
