/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { NgModule, ModuleWithProviders } from '@angular/core';
import { MarkdownAPIClient, USE_DOMAIN, USE_HTTP_OPTIONS } from './markdown-api-client.service';
import { GuardedMarkdownAPIClient } from './guarded-markdown-api-client.service';
import { APIClientModuleConfig } from '../../types';

export { MarkdownAPIClient } from './markdown-api-client.service';
export { MarkdownAPIClientInterface } from './markdown-api-client.interface';
export { GuardedMarkdownAPIClient } from './guarded-markdown-api-client.service';

@NgModule({})
export class MarkdownAPIClientModule {
  /**
   * Use this method in your root module to provide the MarkdownAPIClientModule
   *
   * If you are not providing
   * @param { APIClientModuleConfig } config
   * @returns { ModuleWithProviders }
   */
  static forRoot(config: APIClientModuleConfig = {}): ModuleWithProviders<MarkdownAPIClientModule> {
    return {
      ngModule: MarkdownAPIClientModule,
      providers: [
        ...(config.domain != null ? [{provide: USE_DOMAIN, useValue: config.domain}] : []),
        ...(config.httpOptions ? [{provide: USE_HTTP_OPTIONS, useValue: config.httpOptions}] : []),
        ...(config.guardResponses ? [{provide: MarkdownAPIClient, useClass: GuardedMarkdownAPIClient }] : [MarkdownAPIClient]),
      ]
    };
  }
}
