/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpResponse, HttpEvent } from '@angular/common/http';
import { Observable } from 'rxjs';import { HttpOptions } from './types';

import * as models from './models';
export interface APIClientInterface {
  /**
   * Arguments object for method `getPetById`.
   */
  getPetByIdParams?: {
    /**  ID of pet to return */
    petId: number,
  };

  /**
   * Find pet by ID
   * Returns a single pet
   * Response generated for [ 200 ] HTTP response code.
   */
  getPetById(
    args: Exclude<APIClientInterface['getPetByIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Pet>;
  getPetById(
    args: Exclude<APIClientInterface['getPetByIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Pet>>;
  getPetById(
    args: Exclude<APIClientInterface['getPetByIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Pet>>;

  /**
   * Arguments object for method `updatePetWithForm`.
   */
  updatePetWithFormParams?: {
    /**  ID of pet that needs to be updated */
    petId: number,
    /**  (optional) Updated name of the pet */
    name?: string,
    /**  (optional) Updated status of the pet */
    status?: string,
  };

  /**
   * Updates a pet in the store with form data
   * Response generated for [ default ] HTTP response code.
   */
  updatePetWithForm(
    args: Exclude<APIClientInterface['updatePetWithFormParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  updatePetWithForm(
    args: Exclude<APIClientInterface['updatePetWithFormParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  updatePetWithForm(
    args: Exclude<APIClientInterface['updatePetWithFormParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `deletePet`.
   */
  deletePetParams?: {
    apiKey?: string,
    /**  Pet id to delete */
    petId: number,
  };

  /**
   * Deletes a pet
   * Response generated for [ default ] HTTP response code.
   */
  deletePet(
    args: Exclude<APIClientInterface['deletePetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deletePet(
    args: Exclude<APIClientInterface['deletePetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deletePet(
    args: Exclude<APIClientInterface['deletePetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `uploadFile`.
   */
  uploadFileParams?: {
    /**  ID of pet to update */
    petId: number,
    /**  (optional) Additional data to pass to server */
    additionalMetadata?: string,
    /**  (optional) file to upload */
    file?: File,
  };

  /**
   * uploads an image
   * Response generated for [ 200 ] HTTP response code.
   */
  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.ApiResponse>;
  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.ApiResponse>>;
  uploadFile(
    args: Exclude<APIClientInterface['uploadFileParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.ApiResponse>>;

  /**
   * Arguments object for method `addPet`.
   */
  addPetParams?: {
    /**  Pet object that needs to be added to the store */
    body: models.Pet,
  };

  /**
   * Add a new pet to the store
   * Response generated for [ default ] HTTP response code.
   */
  addPet(
    args: Exclude<APIClientInterface['addPetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  addPet(
    args: Exclude<APIClientInterface['addPetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  addPet(
    args: Exclude<APIClientInterface['addPetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `updatePet`.
   */
  updatePetParams?: {
    /**  Pet object that needs to be added to the store */
    body: models.Pet,
  };

  /**
   * Update an existing pet
   * Response generated for [ default ] HTTP response code.
   */
  updatePet(
    args: Exclude<APIClientInterface['updatePetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  updatePet(
    args: Exclude<APIClientInterface['updatePetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  updatePet(
    args: Exclude<APIClientInterface['updatePetParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `findPetsByStatus`.
   */
  findPetsByStatusParams?: {
    /**  Status values that need to be considered for filter */
    status: ('available' | 'pending' | 'sold')[],
  };

  /**
   * Finds Pets by status
   * Multiple status values can be provided with comma separated strings
   * Response generated for [ 200 ] HTTP response code.
   */
  findPetsByStatus(
    args: Exclude<APIClientInterface['findPetsByStatusParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Pet[]>;
  findPetsByStatus(
    args: Exclude<APIClientInterface['findPetsByStatusParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Pet[]>>;
  findPetsByStatus(
    args: Exclude<APIClientInterface['findPetsByStatusParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Pet[]>>;

  /**
   * Arguments object for method `findPetsByTags`.
   */
  findPetsByTagsParams?: {
    /**  Tags to filter by */
    tags: string[],
  };

  /**
   * Finds Pets by tags
   * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
   * @deprecated this method has been deprecated and may be removed in future.
   * Response generated for [ 200 ] HTTP response code.
   */
  findPetsByTags(
    args: Exclude<APIClientInterface['findPetsByTagsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Pet[]>;
  findPetsByTags(
    args: Exclude<APIClientInterface['findPetsByTagsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Pet[]>>;
  findPetsByTags(
    args: Exclude<APIClientInterface['findPetsByTagsParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Pet[]>>;

  /**
   * Returns pet inventories by status
   * Returns a map of status codes to quantities
   * Response generated for [ 200 ] HTTP response code.
   */
  getInventory(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<{ [key: string]: number }>;
  getInventory(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<{ [key: string]: number }>>;
  getInventory(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<{ [key: string]: number }>>;

  /**
   * Arguments object for method `getOrderById`.
   */
  getOrderByIdParams?: {
    /**  ID of pet that needs to be fetched */
    orderId: number,
  };

  /**
   * Find purchase order by ID
   * For valid response try integer IDs with value >= 1 and <= 10. Other values will generated exceptions
   * Response generated for [ 200 ] HTTP response code.
   */
  getOrderById(
    args: Exclude<APIClientInterface['getOrderByIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Order>;
  getOrderById(
    args: Exclude<APIClientInterface['getOrderByIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Order>>;
  getOrderById(
    args: Exclude<APIClientInterface['getOrderByIdParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Order>>;

  /**
   * Arguments object for method `deleteOrder`.
   */
  deleteOrderParams?: {
    /**  ID of the order that needs to be deleted */
    orderId: number,
  };

  /**
   * Delete purchase order by ID
   * For valid response try integer IDs with positive integer value. Negative or non-integer values will generate API errors
   * Response generated for [ default ] HTTP response code.
   */
  deleteOrder(
    args: Exclude<APIClientInterface['deleteOrderParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deleteOrder(
    args: Exclude<APIClientInterface['deleteOrderParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deleteOrder(
    args: Exclude<APIClientInterface['deleteOrderParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `placeOrder`.
   */
  placeOrderParams?: {
    /**  order placed for purchasing the pet */
    body: models.Order,
  };

  /**
   * Place an order for a pet
   * Response generated for [ 200 ] HTTP response code.
   */
  placeOrder(
    args: Exclude<APIClientInterface['placeOrderParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.Order>;
  placeOrder(
    args: Exclude<APIClientInterface['placeOrderParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.Order>>;
  placeOrder(
    args: Exclude<APIClientInterface['placeOrderParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.Order>>;

  /**
   * Arguments object for method `getUserByName`.
   */
  getUserByNameParams?: {
    /**  The name that needs to be fetched. Use user1 for testing.  */
    username: string,
  };

  /**
   * Get user by user name
   * Response generated for [ 200 ] HTTP response code.
   */
  getUserByName(
    args: Exclude<APIClientInterface['getUserByNameParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.User>;
  getUserByName(
    args: Exclude<APIClientInterface['getUserByNameParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.User>>;
  getUserByName(
    args: Exclude<APIClientInterface['getUserByNameParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.User>>;

  /**
   * Arguments object for method `updateUser`.
   */
  updateUserParams?: {
    /**  name that need to be updated */
    username: string,
    /**  Updated user object */
    body: models.User,
  };

  /**
   * Updated user
   * This can only be done by the logged in user.
   * Response generated for [ default ] HTTP response code.
   */
  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  updateUser(
    args: Exclude<APIClientInterface['updateUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `deleteUser`.
   */
  deleteUserParams?: {
    /**  The name that needs to be deleted */
    username: string,
  };

  /**
   * Delete user
   * This can only be done by the logged in user.
   * Response generated for [ default ] HTTP response code.
   */
  deleteUser(
    args: Exclude<APIClientInterface['deleteUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  deleteUser(
    args: Exclude<APIClientInterface['deleteUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  deleteUser(
    args: Exclude<APIClientInterface['deleteUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `loginUser`.
   */
  loginUserParams?: {
    /**  The user name for login */
    username: string,
    /**  The password for login in clear text */
    password: string,
  };

  /**
   * Logs user into the system
   * Response generated for [ 200 ] HTTP response code.
   */
  loginUser(
    args: Exclude<APIClientInterface['loginUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<string>;
  loginUser(
    args: Exclude<APIClientInterface['loginUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<string>>;
  loginUser(
    args: Exclude<APIClientInterface['loginUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<string>>;

  /**
   * Logs out current logged in user session
   * Response generated for [ default ] HTTP response code.
   */
  logoutUser(
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  logoutUser(
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  logoutUser(
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `createUser`.
   */
  createUserParams?: {
    /**  Created user object */
    body: models.User,
  };

  /**
   * Create user
   * This can only be done by the logged in user.
   * Response generated for [ default ] HTTP response code.
   */
  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  createUser(
    args: Exclude<APIClientInterface['createUserParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `createUsersWithArrayInput`.
   */
  createUsersWithArrayInputParams?: {
    /**  List of user object */
    body: models.User[],
  };

  /**
   * Creates list of users with given input array
   * Response generated for [ default ] HTTP response code.
   */
  createUsersWithArrayInput(
    args: Exclude<APIClientInterface['createUsersWithArrayInputParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  createUsersWithArrayInput(
    args: Exclude<APIClientInterface['createUsersWithArrayInputParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  createUsersWithArrayInput(
    args: Exclude<APIClientInterface['createUsersWithArrayInputParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

  /**
   * Arguments object for method `createUsersWithListInput`.
   */
  createUsersWithListInputParams?: {
    /**  List of user object */
    body: models.User[],
  };

  /**
   * Creates list of users with given input array
   * Response generated for [ default ] HTTP response code.
   */
  createUsersWithListInput(
    args: Exclude<APIClientInterface['createUsersWithListInputParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<void>;
  createUsersWithListInput(
    args: Exclude<APIClientInterface['createUsersWithListInputParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<void>>;
  createUsersWithListInput(
    args: Exclude<APIClientInterface['createUsersWithListInputParams'], undefined>,
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<void>>;

}
