/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import { HttpClient, HttpResponse, HttpEvent } from '@angular/common/http';
import { Inject, Injectable, Optional } from '@angular/core';
import { RateLimitAPIClientInterface } from './rate-limit-api-client.interface';
import { Observable } from 'rxjs';
import { tap } from 'rxjs/operators';
import { USE_DOMAIN, USE_HTTP_OPTIONS, RateLimitAPIClient } from './rate-limit-api-client.service';
import { DefaultHttpOptions, HttpOptions } from '../../types';

import * as models from '../../models';
import * as guards from '../../guards';

@Injectable()
export class GuardedRateLimitAPIClient extends RateLimitAPIClient implements RateLimitAPIClientInterface {

  constructor(
    readonly httpClient: HttpClient,
    @Optional() @Inject(USE_DOMAIN) domain?: string,
    @Optional() @Inject(USE_HTTP_OPTIONS) options?: DefaultHttpOptions,
  ) {
    super(httpClient, domain, options);
  }

  /**
   * Get your current rate limit status
   * Note: Accessing this endpoint does not count against your rate limit.
   *
   * Response generated for [ 200 ] HTTP response code.
   */
  getRateLimit(
    args?: RateLimitAPIClientInterface['getRateLimitParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'body',
  ): Observable<models.RateLimit>;
  getRateLimit(
    args?: RateLimitAPIClientInterface['getRateLimitParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'response',
  ): Observable<HttpResponse<models.RateLimit>>;
  getRateLimit(
    args?: RateLimitAPIClientInterface['getRateLimitParams'],
    requestHttpOptions?: HttpOptions,
    observe?: 'events',
  ): Observable<HttpEvent<models.RateLimit>>;
  getRateLimit(
    args: RateLimitAPIClientInterface['getRateLimitParams'] = {},
    requestHttpOptions?: HttpOptions,
    observe: any = 'body',
  ): Observable<models.RateLimit | HttpResponse<models.RateLimit> | HttpEvent<models.RateLimit>> {

    return super.getRateLimit(args, requestHttpOptions, observe)
      .pipe(tap((res: any) => guards.isRateLimit(res) || console.error(`TypeGuard for response 'models.RateLimit' caught inconsistency.`, res)));
  }

}
