/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export enum Right {
  MEMBER = "MEMBER",
  ADMIN = "ADMIN",
  VIEW_ALL = "VIEW_ALL",
  VIEW_MY = "VIEW_MY",
  VIEW_EDIT = "VIEW_EDIT",
  READ_WRITE = "READ WRITE",
  CONTROL = "CONTROL",
}
