/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


export interface TestModel {
  /** '汉字' escaped is '\u6c49\u5b57' */
  '\u6c49\u5b57'?: string;
  /** '42test' */
  '42test'?: string;
  /** 'anotherKey@' */
  'anotherKey@'?: string;
  /** 'some-key' */
  'some-key'?: string;
  /** 'yet@notherKey' */
  'yet@notherKey'?: string;
  /** $name */
  $name?: string;
  /** sum of everything there is converted to bananas */
  count?: number;
}
