/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import {
  V1ContentModelObject,
} from '.';

export interface V1ContentModelVersion {
  contentModelId?: string;
  contentModelVersionId?: string;
  createdAt?: string;
  nextVersionId?: string;
  previousVersionId?: string;
  schema?: V1ContentModelObject;
}
