/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * The response for Firestore.BeginTransaction.
 */
export interface BeginTransactionResponse {
  transaction?: string;  // The transaction that was started.
}
