/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * A selection of a collection, such as `messages as m1`.
 */
export interface CollectionSelector {
  allDescendants?: boolean;  // When false, selects only collections that are immediate children ofthe `parent` specified in the containing `RunQueryRequest`.When true, selects all descendant collections.
  collectionId?: string;  // The collection ID.When set, selects only collections with this ID.
}
