/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import {
  Filter,
} from '.';

/**
 * A filter that merges multiple other filters using the given operator.
 */
export interface CompositeFilter {
  /**
   * The list of filters to combine.
   * Must contain at least one filter.
   */
  filters?: Filter[];
  /** The operator for combining multiple filters. */
  op?: ('OPERATOR_UNSPECIFIED' | 'AND');
}
