/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */


/**
 * A target specified by a set of documents names.
 */
export interface DocumentsTarget {
  /** The names of the documents to retrieve. In the format:`projects/{project_id}/databases/{database_id}/documents/{document_path}`.The request will fail if any of the document is not a child resource ofthe given `database`. Duplicate names will be elided. */
  documents?: string[];
}
