/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import {
  DocumentChange,
  DocumentDelete,
  DocumentRemove,
  ExistenceFilter,
  TargetChange,
} from '.';

/**
 * The response for Firestore.Listen.
 */
export interface ListenResponse {
  /** A Document has changed. */
  documentChange?: DocumentChange;
  /** A Document has been deleted. */
  documentDelete?: DocumentDelete;
  /**
   * A Document has been removed from a target (because it is no longer
   * relevant to that target).
   */
  documentRemove?: DocumentRemove;
  /**
   * A filter to apply to the set of documents previously returned for the
   * given target.
   * 
   * 
   * Returned when documents may have been removed from the given target, but
   * the exact documents are unknown.
   */
  filter?: ExistenceFilter;
  /** Targets have changed. */
  targetChange?: TargetChange;
}
