/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import {
  Index,
} from '.';

/**
 * The response for FirestoreAdmin.ListIndexes.
 */
export interface ListIndexesResponse {
  indexes?: Index[];  // The indexes.
  nextPageToken?: string;  // The standard List next-page token.
}
