/**
 * This file is auto-generated by the API client generator.
 * https://github.com/flowup/api-client-generator
 *
 * Avoid editing this file manually unless necessary.
 * Please report any bugs so they can be addressed in future versions.
 */

/* tslint:disable */
/* eslint-disable */

import {
  Document,
} from '.';

/**
 * The response for Firestore.RunQuery.
 */
export interface RunQueryResponse {
  /** A query result.Not set when reporting partial progress. */
  document?: Document;
  /** The time at which the document was read. This may be monotonicallyincreasing; in this case, the previous documents in the result stream areguaranteed not to have changed between their `read_time` and this one.If the query returns no results, a response with `read_time` and no`document` will be sent, and this represents the time at which the querywas run. */
  readTime?: string;
  /** The number of results that have been skipped due to an offset betweenthe last response and the current response. */
  skippedResults?: number;
  /** The transaction that was started as part of this request.Can only be set in the first response, and only ifRunQueryRequest.new_transaction was set in the request.If set, no other fields will be set in this response. */
  transaction?: string;
}
